#INCLUDE "Zscript/Spawners.zsc"
#INCLUDE "Zscript/Weapons.zsc"
#INCLUDE "Zscript/SFX.zsc"
#INCLUDE "Zscript/Monsters.zsc"
#INCLUDE "Zscript/Pickups.zsc"
#INCLUDE "Zscript/Upgrades.zsc"
#INCLUDE "Zscript/Perks.zsc"
#INCLUDE "Zscript/Decor.zsc"
#INCLUDE "Zscript/ExWeapons.zsc"
#INCLUDE "Zscript/Tokens.zsc"
#INCLUDE "Zscript/DemonRune.zsc"

//=================
// Complex Doomguy
//=================

Class ComplexDoomPlayer : DoomPlayer
{
Default
{
Speed 1
Health 100
GibHealth 60
Radius 16
Height 56
Mass 100
PainChance 255
Species "Player"
DamageFactor "DemonPlayer", 0.0
Player.SoundClass "Marine"
Player.ColorRange 112, 127
Player.DisplayName "Doom Guy"
//Player.CrouchSprite "PLYC"
Player.StartItem "Handgun"
//Player.StartItem "Frag Grenade"
Player.StartItem "HandGrenadeAmmo" 2
//Player.StartItem "Land Mine"
Player.StartItem "MineAmmo" 2
Player.StartItem "Melee"
Player.StartItem "BulletMag" 60
Player.StartItem "PistolMagazine" 16
Player.StartItem "RevolverCylinder" 6
Player.StartItem "ShotgunMagazine" 9
Player.StartItem "SSGShell" 2
Player.StartItem "ShotgunDrum" 9
Player.StartItem "QuadShell" 4
Player.StartItem "ARMagazine" 41
Player.StartItem "ARGrenade" 1
Player.StartItem "RocketDrum" 7
Player.StartItem "GrenadeDrum" 7
Player.StartItem "PlasmaCell" 50
Player.StartItem "DemonMagazine" 50
Player.StartItem "CellCharge" 5
Player.StartItem "BFGCellCharge" 5
Player.StartItem "DTBFGCellCharge" 1
Player.StartItem "MP40Mag" 33
Player.StartItem "StartingArmor"
Player.StartItem "StartingArmorToken" 1
Player.StartItem "MeleeEquipped" 1
Player.StartItem "ChainsawEquipped" 1
Player.StartItem "PistolEquipped" 1
Player.StartItem "RevolverEquipped" 1
Player.StartItem "ShotgunEquipped" 1
Player.StartItem "ASGEquipped" 1
Player.StartItem "SSGEquipped" 1
Player.StartItem "QSGEquipped" 1
//+NOSKIN
States
{
Spawn:
	TNT1 A 0
	TNT1 A 0 A_JumpIfInventory("InDemonForm",1,"IsHuman")
    PLAY A 5
    Loop
IsHuman:
	PLAY A 1
	TNT1 A 0 A_TakeInventory("InDemonForm",1)
	TNT1 A 0 A_JumpIfInventory("FrenzyToken",1,"HasFrenzy")
	Goto Spawn
HasFrenzy:
	TNT1 A 0 A_GiveInventory("FrenzyGiver",1)
	Goto Spawn
See:
	PLAY ABCD 4
	Goto Spawn
Missile:
	PLAY E 12
	Goto Spawn
Melee:
	PLAY F 6 Bright
	Goto Missile
Pain:
	TNT1 A 0
	TNT1 A 0 A_JumpIfInventory("BasicArmor",1,"ArmorChecked")
	TNT1 A 0 A_TakeInventory("StartingArmorToken",1)
	TNT1 A 0 A_TakeInventory("GreenArmorToken",1)
	TNT1 A 0 A_TakeInventory("BlueArmorToken",1)
	TNT1 A 0 A_TakeInventory("RedArmorToken",1)
	TNT1 A 0 A_JumpIfInventory("NoArmorToken",1,"ArmorChecked")
	TNT1 A 0 A_GiveInventory("NoArmorToken",1)
ArmorChecked:
	PLAY G 4 
	PLAY G 4 A_Pain
	Goto Spawn
Death:
	TNT1 A 0
	TNT1 A 0 A_TakeInventory("MeleeCombo")
	TNT1 A 0 A_TakeInventory("MeleeCombo2")
	TNT1 A 0 A_TakeInventory("MeleeCombo3")
	TNT1 A 0 A_TakeInventory("MeleeCombo4")
	TNT1 A 0 A_TakeInventory("ChainsawCombo")
	TNT1 A 0 A_TakeInventory("ChainsawCombo2")
	TNT1 A 0 A_TakeInventory("ChainsawCombo3")
	TNT1 A 0 A_TakeInventory("BootAction",1)
	TNT1 A 0 A_TakeInventory("HandGrenadeAction",1)
	TNT1 A 0 A_TakeInventory("MineAction",1)
	TNT1 A 0 A_TakeInventory("UsingPistol",1)
	TNT1 A 0 A_TakeInventory("AssaultRifleToken",1)
	TNT1 A 0 A_TakeInventory("MinigunToken",1)
	TNT1 A 0 A_TakeInventory("MinigunToken2",1)
	TNT1 A 0 A_TakeInventory("RocketLauncherCycled",1)
	TNT1 A 0 A_TakeInventory("RocketLauncherToken",1)
	TNT1 A 0 A_TakeInventory("PlasmaRifleCharged",1)
	TNT1 A 0 A_TakeInventory("RailgunAction",1)
	TNT1 A 0 A_TakeInventory("WeaponSpecialAction",1)
	TNT1 A 0 A_TakeInventory("FuriousToken",1)
	TNT1 A 0 A_TakeInventory("StartingArmorToken")
	TNT1 A 0 A_TakeInventory("GreenArmorToken",1)
	TNT1 A 0 A_TakeInventory("BlueArmorToken",1)
	TNT1 A 0 A_TakeInventory("RedArmorToken",1)
	TNT1 A 0 A_StopSoundEx("SoundSlot5")
	PLAY H 8
	PLAY I 8 A_PlayerScream
	PLAY J 8 A_NoBlocking
	PLAY K 8
	PLAY L 8 A_SpawnItem("BodyCrash",0,0,0,0)
	PLAY M 8
	PLAY N -1
	Stop
XDeath:
	TNT1 A 0
	TNT1 A 0 A_TakeInventory("MeleeCombo")
	TNT1 A 0 A_TakeInventory("MeleeCombo2")
	TNT1 A 0 A_TakeInventory("MeleeCombo3")
	TNT1 A 0 A_TakeInventory("MeleeCombo4")
	TNT1 A 0 A_TakeInventory("ChainsawCombo")
	TNT1 A 0 A_TakeInventory("ChainsawCombo2")
	TNT1 A 0 A_TakeInventory("ChainsawCombo3")
	TNT1 A 0 A_TakeInventory("BootAction",1)
	TNT1 A 0 A_TakeInventory("HandGrenadeAction",1)
	TNT1 A 0 A_TakeInventory("MineAction",1)
	TNT1 A 0 A_TakeInventory("UsingPistol",1)
	TNT1 A 0 A_TakeInventory("AssaultRifleToken",1)
	TNT1 A 0 A_TakeInventory("MinigunToken",1)
	TNT1 A 0 A_TakeInventory("MinigunToken2",1)
	TNT1 A 0 A_TakeInventory("RocketLauncherCycled",1)
	TNT1 A 0 A_TakeInventory("RocketLauncherToken",1)
	TNT1 A 0 A_TakeInventory("PlasmaRifleCharged",1)
	TNT1 A 0 A_TakeInventory("RailgunAction",1)
	TNT1 A 0 A_TakeInventory("WeaponSpecialAction",1)
	TNT1 A 0 A_TakeInventory("FuriousToken",1)
	TNT1 A 0 A_TakeInventory("StartingArmorToken")
	TNT1 A 0 A_TakeInventory("GreenArmorToken",1)
	TNT1 A 0 A_TakeInventory("BlueArmorToken",1)
	TNT1 A 0 A_TakeInventory("RedArmorToken",1)
	TNT1 A 0 A_StopSoundEx("SoundSlot5")
	PLAY P 3
	PLAY Q 3 A_XScream
	PLAY R 3 A_SpawnItemEx("GibbedGenerator",0,0,0,0,0,0,0,128)
	PLAY S 3 A_NoBlocking
	PLAY TUV 3
	PLAY W -1
	Stop      
	}
}
